### ISSUE TITLE
gpu autodetect not working

### ISSUE THREAD

**Issue by MSiggel** [bio-phys/capriqorn#2]
using the autodetect flag
```
workers: -1
```
assumes there are no gpus on the cluster whereas two are available. When setting the number of cores explicitly this works fine and there is a significant performance improvement between using 0,1,2 GPUs

**Comment by reuterk** [comment]
This issue is now fixed with the most recent commit in the Cadishi repository.

**Comment by reuterk** [comment]
an improved fix was committed today
