### ISSUE TITLE
Error messages for erroneous yaml files unclear

### ISSUE THREAD

**Issue by MSiggel** [bio-phys/capriqorn#3]
yaml files which have a missing colons or otherwise falsely formatted throw the following error: 
```
Error: Could not read input File 'histograms.yaml'.
```
As I understood it at first, it implied the file didn't exist in the working directory, however, it refers to errors in the existing file. Perhaps an error message such as "formatting error in input file "histograms.yaml" would be useful. Especially for users not familiar with the yaml input format this could be more helpful.

**Comment by reuterk** [comment]
The parameter file reader now gives the line and column number in case of a malformatted YAML file. Please note that it is part of the Cadishi package, not Capriqorn.
