### ISSUE TITLE
Visible benchmarking information

### ISSUE THREAD

**Issue by MSiggel** [bio-phys/capriqorn#4]
Currently when running capriqorn histo on the cluster no information is written to the log file until the end of the run.
Related to #1 it would be good to print benachmarking information to the log file. An estimate as to how long individual runs might last so their walltime can be adjusted accordingly.

**Comment by reuterk** [comment]
In histograms.yaml, you have the "expert" parameter
```
output:
  flush_interval: 100
```
which is set to 100 by default.

It specifies the number of frames between flushes of stdout and (implemented newly today) the HDF5 file. Setting this parameter to a reasonable value should give you the possibility to watch your runs, and in addition the HDF5 file should contain the already processed data even in case the run was killed by the batch system.

Please be careful with high flush frequencies as this has the potential to severely degrade the performance of a parallel shared file system for all users.

**Comment by reuterk** [comment]
An estimation of the total runtime was added to

`histograms_output/histo_sum_worker.log`

Again, this refers to the Cadishi package, not Capriqorn.
